### ISSUE TITLE
Sudden 500 Error

### ISSUE THREAD

**Issue by dzy969** [dezrez/DezrezCoreAPI#63] opened 2018-02-28 15:31 UTC
Hi, 
In the last day we are getting 500 errors in response to submitting viewing feedback via the API.  We have released any code for a couple of months so I dont think anything has changed at our end.

Has anything changed your end?
Dean

**Comment by dendle** [comment] 2018-02-28 15:40
Hello Dean,
Sorry to hear that you are getting errors from our API - let me look into this for you.

It would be much quicker if you could provide an error reference/guid so that I can track the request - could you provide this?

Ideally, you would also have the request URL to hand and the contents, but I realise this is not always possible.

Any more information you can provide would be great

Thanks,
Matt

**Comment by dzy969** [comment] 2018-02-28 16:41
Hi Matt,
Request URL is https://api.dezrez.com/api/viewing/41487023/recordfeedback?AgencyId=84&branchId=648405

Contents
`{"FeedbackId":null,"Feedback":"Match requirements:\r\n0.\r\n\r\nCondition of the property:\r\n0.\r\n\r\nValue for money:\r\n0.\r\n\r\nWould you Like us to contact you regarding this viewing?\r\nNo.\r\n\r\nOther comments:\r\nTest by Dean - Please ignore.","FeedbackDate":"2018-02-28T16:28:57.6555191+00:00","NegIds":null,"Impression":null,"ApplicableToGroupIds":null}`

I dont have anything useful on the response except its 'The remote server returned an error: (500) Internal Server Error.'

Thanks
Dean

**Comment by dendle** [comment] 2018-02-28 17:18
All API errors should come back with a JSON error, so that fact that it hasn't is strange.

Can you dig into the response headers and supply those?

In the meantime, i'll try and replicate the issue here...

**Comment by marc-harry** [comment] 2018-03-01 12:35
Hi Dean (@dzy969 ),

I've been looking into the error you've been getting there isn't anything wrong with the data you are passing into that request. 
As Matt suggested do you get anything else in the error response body. If not could you look for the response header named: Dezrez-Trace-Guid and provide us with the guid value, I will hopefully then be able to narrow down the cause of the issue.

Thanks,
Marc

**Comment by dzy969** [comment] 2018-03-01 12:59
Hi Marc,
Here are the headers.

{Pragma: no-cache
Dezrez-Trace-Guid: 86295dac-ae31-4b81-bdfb-d9eec6091f0d
Request-Context: appId=cid-v1:c6bdbebd-0fa4-448a-8a0c-5faaa8b30c2e
Content-Length: 311
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Thu, 01 Mar 2018 12:56:56 GMT
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

}

**Comment by marc-harry** [comment] 2018-03-01 15:01
Hi Dean,

Thank you for that using that information, I was also able to replicate the issue here. I have put in a fix for this issue and hopefully it should be deployed to the live environment as soon as it has been approved by our quality assurance team.

Thanks,
Marc

**Comment by dzy969** [comment] 2018-03-06 12:07
Hi Marc,
Do you know if the fix is now live?
Thanks

**Comment by marc-harry** [comment] 2018-03-07 08:15
Hi Dean, (@dzy969)

The fix for this is now live. And this error should no longer occur.

Thanks,
Marc

**Closed as completed by marc-harry** 2018-03-07 08:15 UTC
